@HOST=http://localhost:8080

## user route index
GET {{HOST}}/user

### user login
POST {{HOST}}/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

### pipe route index
GET {{HOST}}/pipe

### List pipes
GET {{HOST}}/pipe/list

### Add pipe
POST {{HOST}}/pipe/add
Content-Type: application/json

{
    "id": "test",
    "input": {
        "url": "rtsp://172.31.169.114:8554/ff/d4jkxuesheng.mp4"
    },
    "outputs": [
        // {
        //     "t": "net",
        //    "net": {
        //         "url": "rtsp://172.31.169.114:8554/ff/d4jkxuesheng.mp4",
        //         "format": "rtsp"
        //    }
        // },
        {
            "t": "zlm",
            "zlm": {
                "app": "shiben",
                "stream": "2"
            }
        }
    ]
}

### Remove pipe
GET {{HOST}}/pipe/remove/test


### system route index
GET {{HOST}}/system

### List devices
GET {{HOST}}/system/list/devices
Content-Type: application/json

{
    "kind": 1,
    "direction": 0
}